### PR TITLE
Add get_dataset_with_hall_number and NULL checks

### PR DESCRIPTION
**Pull request by kbarros**
This would address https://github.com/singularitti/Spglib.jl/issues/76

### CODE REVIEW

**Comment by kbarros** [comment]
Hello, this pull request would fix the issue with checking for NULL, but not the issue with the memory leak. It's not passing the formatting check, but I don't know why (running Julia formatter inside VSCode does not answer the question either). Could you possibly help to figure out why CI did not accept the formatting?

**Comment by hsugawa8651** [comment]
Your fix for checking NULL looks fine.

I suppose that the format error is because `docs/portability.md` is missing.
Would you try delete "portability.md" line in `docs/index.md` ?

**Comment by kbarros** [comment]
With that new change, CI now says "restyling found differences". I'm not familiar with this system, so don't know how to proceed.

**Comment by kbarros** [comment]
The diff in the pull request is trivial. Maybe someone else can try it and see if they can get past the CI formatting issue?

**Comment by singularitti** [comment]
Thank you @kbarros @hsugawa8651 !

I fix the docs of `get_dataset_with_hall_number`. I believe you forgot to type `hall_number` in its docs, right @kbarros ?
Don't worry about the formatting check. As long as the code is right, I will merge it.

**Pull request merged**
